ENT-11607 - Kotlin/JDK compatibility
corda/corda-shell pull request #99
Opened 2024-03-08 13:04 UTC by chriscochrane

Tests were previously failing with errors like this:

`Unable to load CorDapp /Users/chris.cochrane/dev/git/corda/corda-shell/shell/build/node-driver/20240308-095001.060-908F4AD1C9C04C13/AliceCorp/cordapps/custom-cordapp_1_140_f9f3b6e7-1c56-428a-813e-dc86624da8ca.jar: Unsupported Kotlin metadata version 1.8.0`

The Kotlin options in `build.gradle `have been updated from 1.8 to 1.9 to resolve this.

Subsequently, it was discovered that tests would then fail with error of the type:

`Unable to make protected <method> accessible: module <module name> does not opens <package name> to unnamed module <address>
`
These are resolved by extending the list of `--add-opens` arguments for the integration test JVM args.

2024-03-08 14:01 UTC, shamsasari requested changes
Can you also update the `kotlinVersion` in gradle.properties to the latest version.

Also, does executing the standalone shell outside of tests work?

2024-03-11 10:34 UTC, chriscochrane commented
> Can you also update the `kotlinVersion` in gradle.properties to the latest version.
> 
> Also, does executing the standalone shell outside of tests work?

@shamsasari 
Made that update, Kotlin 1.9.23, thanks.

Yes, I did indeed try the standalone shell outside of the tests and it works/connects OK. The number of available commands was much reduced when compared to the direct SSH connection. Is that expected?

2024-03-11 11:08 UTC, adelel1 approved these changes, later dismissed

2024-03-11 11:14 UTC, shamsasari commented on shell/build.gradle
> +
revert

2024-03-11 11:15 UTC, shamsasari commented on shell/build.gradle
>              '--add-exports', 'java.base/sun.nio.ch=ALL-UNNAMED'
Can you try removing this and see if it works. I have a feeling it's not needed

2024-03-11 11:15 UTC, shamsasari commented on shell/build.gradle
>              '--add-opens', 'java.base/java.lang=ALL-UNNAMED',
The existing `--add-opens`, can you put them one per line.

2024-03-11 11:19 UTC, shamsasari commented
>Yes, I did indeed try the standalone shell outside of the tests and it works/connects OK.

I'm surprised by that. Why do the integration tests need all those `--add-opens` flags? The `Add-Opens` manifest attribute for the standalone jar (see standalone-shell/build.gradle) only has a few packages listed. 

>The number of available commands was much reduced when compared to the direct SSH connection. Is that expected?

I wouldn't have thought so. Is there anything in the logs?

2024-03-11 12:24 UTC, shamsasari approved these changes

2024-03-11 13:04 UTC, merged